name: domain_investor
description: Team Phi
version: 0.0.2
author:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  built_value: ^7.0.8
  built_collection: ^4.3.2
  quartet: ^0.1.1
  dio: 3.0.9
  provider: ^4.0.4
  get_it: ^3.1.0
  google_fonts: ^0.3.9
  http: ^0.12.0+4
  intl: ^0.16.0
  shimmer: 1.1.0
  dio_cookie_manager: 1.0.0
  path_provider: ^1.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.3
  built_value_generator: ^7.0.8

flutter:
  uses-material-design: true
  assets:
    - assets/godaddy_2020_logo.png
    - assets/ic_account.png
    - assets/ic_home.png
    - assets/ic_manage.png
    - assets/ic_lock.png
    - assets/ic_renew.png
    - assets/govalue.png
  fonts:
    - family: Sage
      fonts:
        - asset: fonts/GD-Sage-Bold.ttf
        - asset: fonts/GD-Sage-Medium.ttf
          weight: 500
    - family: GDSherpa
      fonts:
        - asset: fonts/GDSherpa-Regular.otf
        - asset: fonts/GDSherpa-Bold.otf
          weight: 700
